# Generated by Django 5.2.3 on 2025-06-20 16:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aredoapp', '0002_country_university'),
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('degreenum', models.CharField(max_length=20)),
                ('passport', models.CharField(max_length=20)),
                ('degree', models.CharField(choices=[('bachelor', 'Bachelor'), ('master', 'Master'), ('phd', 'PhD')], max_length=20)),
                ('department', models.CharField(max_length=100)),
                ('deepdepartment', models.CharField(max_length=100)),
                ('grad_uniBach', models.CharField(max_length=100)),
                ('grad_unimaster', models.CharField(max_length=100)),
                ('traker', models.CharField(max_length=100)),
                ('fees', models.CharField(max_length=100)),
                ('pdf', models.CharField(max_length=100)),
                ('date_applied', models.DateTimeField(auto_now_add=True)),
                ('payoff', models.BooleanField(default=False)),
                ('submitted', models.BooleanField(default=False)),
                ('approved', models.BooleanField(default=False)),
                ('accepted', models.BooleanField(default=False)),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applicants', to='aredoapp.university')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
