# Generated by Django 5.2.3 on 2025-07-26 10:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aredoapp', '0003_applicant'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head', models.CharField(max_length=255)),
                ('content', models.CharField(max_length=3000)),
                ('pic', models.FileField(upload_to='news/')),
            ],
        ),
        migrations.RenameField(
            model_name='applicant',
            old_name='grad_uniBach',
            new_name='grad_univerBach',
        ),
        migrations.RenameField(
            model_name='applicant',
            old_name='grad_unimaster',
            new_name='grad_univermaster',
        ),
        migrations.RenameField(
            model_name='applicant',
            old_name='payoff',
            new_name='touch',
        ),
        migrations.AlterField(
            model_name='applicant',
            name='pdf',
            field=models.FileField(upload_to='applicant/'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='traker',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='CancelCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=255)),
                ('traker', models.CharField(max_length=255)),
                ('pdf', models.FileField(upload_to='cancelcode/')),
                ('touch', models.BooleanField(default=False)),
                ('fees', models.CharField(max_length=100)),
                ('submitted', models.BooleanField(default=False)),
                ('approved', models.BooleanField(default=False)),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cancelcode', to='aredoapp.university')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cancelcode', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LangCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=255)),
                ('passport', models.CharField(max_length=255)),
                ('traker', models.CharField(max_length=255)),
                ('pdf', models.FileField(upload_to='lang/')),
                ('touch', models.BooleanField(default=False)),
                ('fees', models.CharField(max_length=100)),
                ('submitted', models.BooleanField(default=False)),
                ('accepted', models.BooleanField(default=False)),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='langcourse', to='aredoapp.university')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='langcourse', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Publish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=255)),
                ('pages', models.CharField(max_length=255)),
                ('magazine', models.CharField(max_length=255)),
                ('mushref', models.CharField(max_length=255)),
                ('publishResearch', models.BooleanField(default=False)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('stilal', models.BooleanField(default=False)),
                ('international', models.BooleanField(default=False)),
                ('touch', models.BooleanField(default=False)),
                ('fees', models.CharField(max_length=100)),
                ('payoff', models.BooleanField(default=False)),
                ('submitted', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publish', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Translate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('nearestPoint', models.CharField(max_length=255)),
                ('govern', models.CharField(choices=[('baghdad', 'Baghdad'), ('anbar', 'Anbar'), ('basra', 'Basra'), ('dhi_qar', 'Dhi Qar'), ('maysan', 'Maysan'), ('muthanna', 'Muthanna'), ('najaf', 'Najaf'), ('karbala', 'Karbala'), ('babil', 'Babil'), ('wasit', 'Wasit'), ('diwaniya', 'Diwaniya'), ('diyala', 'Diyala'), ('kirkuk', 'Kirkuk'), ('ninawa', 'Ninawa'), ('salah_al_din', 'Salah al-Din'), ('duhok', 'Duhok'), ('erbil', 'Erbil'), ('sulaymaniyah', 'Sulaymaniyah'), ('halabja', 'Halabja')], max_length=20)),
                ('touch', models.BooleanField(default=False)),
                ('fees', models.CharField(max_length=100)),
                ('received', models.BooleanField(default=False)),
                ('submitted', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translate', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Universityfees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=255)),
                ('univerFees', models.CharField(max_length=255)),
                ('kind', models.CharField(max_length=255)),
                ('touch', models.BooleanField(default=False)),
                ('payoff', models.BooleanField(default=False)),
                ('fees', models.CharField(max_length=100)),
                ('submitted', models.BooleanField(default=False)),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fees', to='aredoapp.university')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fees', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
